#!/bin/sh

export IGNOREEOF=10
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=vim
export PAGER=less
export HISTCONTROL=ignoredups

for file in ~/.sh/* ; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

if [ -d ~/.composer/vendor/bin ]; then
    COMPOSER_MEMORY_LIMIT=-1
    export COMPOSER_MEMORY_LIMIT
    PATH=~/.composer/vendor/bin:$PATH
fi

if [ -d ~/bin ]; then
    PATH=~/bin:$PATH
fi

if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
