#!/bin/bash
composer global -qn update
composer global -qn install

nvim -u $HOME/.config/nvim/init.vim +PlugInstall +qa

bash $HOME/.vim/plug/gruvbox/gruvbox_256palette.sh
if [ ! -e $HOME/.config/kitty/theme.conf ]; then
    ln $HOME/.config/kitty/kitty-themes/gruvbox_dark.conf $HOME/.config/kitty/theme.conf
fi

[ -d ~/bin ] || mkdir ~/bin
ln -fs $(dirname $(pwd))/.git-scripts/* ~/bin/
